/* Create table r_rainfall in weather schema*/
CREATE TABLE `weather`.`r_rainfall` (
	`id` BIGINT(20) NOT NULL AUTO_INCREMENT,
	`timestamp` DATETIME NULL DEFAULT NULL,
	`station_id` VARCHAR(50) NULL DEFAULT NULL,
	`value` INT(11) NULL DEFAULT NULL,
    `nea_id` VARCHAR(50) NULL DEFAULT NULL,
	`device_id` VARCHAR(50) NULL DEFAULT NULL,
	`name` VARCHAR(255) NULL DEFAULT NULL,
	`loc_lat` DECIMAL(10, 6) NULL DEFAULT NULL,
	`loc_lon` DECIMAL(10, 6) NULL DEFAULT NULL,
	PRIMARY KEY (`id`) USING BTREE
)
ENGINE=InnoDB
;
