name: ci

on:
  push:
    branches-ignore:
      - main
  pull_request:
    branches: main

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      CONFIG_DIR: ${{ github.workspace }}/config
      KEY_DIR: ${{ github.workspace }}/keys
      PYTHONPATH: ${{ github.workspace }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v6.0.0
        with:
          python-version: "3.12.3"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Lint with flake8
        run: |
          flake8  --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8  --count --max-complexity=10 --ignore=W291 --statistics

      - name: Create dummy
        run: |
          mkdir -p $HOME/keys
          echo "dummy_key" > $HOME/keys/key_lta.txt

      - name: Create dummy key
        run: |
          mkdir -p $HOME/keys
          echo "dummy_key" > $HOME/keys/key_lta.txt

      - name: Run tests
        run: pytest tests/
